# Generated by Django 4.1.5 on 2023-02-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_id', models.CharField(max_length=50)),
                ('product_image', models.ImageField(upload_to='')),
                ('production_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('product_description', models.TextField(max_length=500)),
                ('sold_date', models.DateField()),
                ('product_sold_location', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
