# Generated by Django 4.1.5 on 2023-02-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_barcodes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barcodes',
            name='barcode',
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.ImageField(default='image', upload_to=''),
        ),
    ]
