# Generated by Django 4.1.5 on 2023-02-11 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_barcodes_barcode_product_barcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Barcodes',
        ),
    ]
