# Generated by Django 4.1.5 on 2023-02-11 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_barcode_alter_product_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=1000)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('user_ip', models.CharField(max_length=60)),
            ],
        ),
    ]
