# Generated by Django 4.1.5 on 2023-02-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_fakeproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.FileField(default='image', upload_to='media'),
        ),
    ]
