# Generated by Django 4.1.5 on 2023-02-26 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_rename_location_fakeproduct_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fakeproduct',
            name='user_ip',
        ),
    ]
