# Generated by Django 4.1.5 on 2023-03-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_fakeproduct_user_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='fakeproduct',
            name='detained',
            field=models.BooleanField(default=False),
        ),
    ]
