# Generated by Django 4.1.5 on 2023-03-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_fakeproduct_detained'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active_ingredient',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
