# Generated by Django 4.1.5 on 2023-03-04 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_active_ingredient_product_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='active_ingredient',
        ),
    ]
