# Generated by Django 4.1.5 on 2023-03-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_product_active_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_manufacturer',
            field=models.CharField(max_length=100),
        ),
    ]
