# Generated by Django 4.1.5 on 2023-03-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_product_product_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiry_date',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='production_date',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
